version: '3'

services:
    db_dev:
        image: mysql:5.7.21
        ports:
          - "3306:3306"
        environment:
          - MYSQL_ROOT_PASSWORD=password
          - MYSQL_DATABASE=database
          - MYSQL_USER=user
          - MYSQL_USER_PASSWORD=password
